auto register vector classes with awkward
scikit-hep/pylhe pull request #195
Opened 2023-04-14 20:15 UTC by tomeichlersmith

Both `vector` and `awkward` are required dependencies of `pylhe` at this time, so this PR proposes to make the registration of the vector classes that `pylhe` uses automatic. This means that the registration function would become a no-operation to maintain backwards compatibility and future scripts wouldn't have to worry about calling it.

Closes #194 .

## Questions
- [ ] Is there a deprecation flag/decorator/documentation that I should add to that function?
- [ ] Should I remove that registration function all-together? It would break the API, but it also is an easy thing to fix for users (just don't use that function anymore since it happens automatically).
- [ ] Add a test showing that the vector helpers work when accessed via a awkward array built by pylhe?

2023-04-14 21:06 UTC, matthewfeickert requested changes
Thanks for your PR @tomeichlersmith. This looks pretty good, and I just have a few small suggestions. :+1:

2023-04-14 21:06 UTC, matthewfeickert commented on src/pylhe/awkward.py
> +    pass
I'd prefer to use the system we have for `pyhf` of giving an explicit deprecated API warning with a removal version (2 minor releases). c.f.

* https://github.com/scikit-hep/pyhf/blob/d6208cbabb8ab727f201e6e06673f938d77b14b2/src/pyhf/exceptions/__init__.py#L181-L190
* https://github.com/scikit-hep/pyhf/blob/d6208cbabb8ab727f201e6e06673f938d77b14b2/src/pyhf/infer/intervals/__init__.py#L11-L30

No need to make an exceptions system here, I was just showing what the warning system looks like.

2023-04-14 21:06 UTC, matthewfeickert commented on src/pylhe/awkward.py
> +# we can call thost helper functions
```suggestion
# Register Awkward behaviors
```

2023-04-14 21:06 UTC, matthewfeickert commented on tests/test_api.py
> +        pylhe.register_awkward()
This should be its own test. c.f. https://github.com/scikit-hep/pyhf/blob/d6208cbabb8ab727f201e6e06673f938d77b14b2/tests/test_regression.py#L183-L196 as an example, but doesn't need to be as detailed as that test.

2023-04-14 21:06 UTC, matthewfeickert commented on tests/test_awkward.py
> +    #    is called on each particle's momentum
```suggestion
```

This commentary is good for the PR body, but isn't really helpful in the tests. If test aren't clear what they're doing then they should get a docstring, not comments.

2023-04-17 21:35 UTC, eduardo-rodrigues commented on tests/test_awkward.py
> +    """awkward registration should correctly happen on import
```suggestion
    """Awkward registration should correctly happen on import.
```

2023-04-17 21:35 UTC, eduardo-rodrigues commented on tests/test_awkward.py
> +    make sure vector helper classes function properly by calling
```suggestion
    Make sure vector helper classes function properly by calling
```

2023-04-17 21:37 UTC, eduardo-rodrigues commented
This sounds very good. @tomeichlersmith, would it make sense to enhance the notebook example a little bit to show how easier it is now to perform calculations such as invariant masser or cone distances or ...?

Otherwise I'm ready to approve.

Many thanks.

2023-04-17 21:42 UTC, tomeichlersmith commented
The `awkward_example` jupyter notebook already uses the vector method `mass` to calculate the invariant mass of two particles, but I could look at updating `zpeak`. Where is the `unweighted_events.lhe` file that is referenced in that example?

2023-04-17 21:47 UTC, eduardo-rodrigues commented
Indeed - I should have checked.

The zpeak notebook needs to be updated since the LHE file it mentions is not in the package nor in scikit-hep-testdata, I recall. It would deserve a new test file ... In that respect, BTW, since you say you regularly use pylhe, would you happen to have interesting (small) files to enhance the test suite in scikit-hep-testdata? We are always keen on having better coverage.

2023-04-17 21:47 UTC, eduardo-rodrigues approved these changes

2023-04-17 21:57 UTC, tomeichlersmith commented
I just used the drell-yan test example for the zpeak and it appears to be the same file (the first two events are the same graphs as before).

I've already included my small and interesting file :smile: It was needed for PR #180 to show that a unregistered PDG ID can exist in the LHE file and the graph can still be rendered.

2023-04-18 11:20 UTC, eduardo-rodrigues commented
Ah ha, thanks, I knew I had exchanged with you already in the past - too many repos and pull requests ;-).

2023-04-18 11:22 UTC, eduardo-rodrigues approved these changes
This seems ready to me. On to @matthewfeickert. Approving.

2023-04-20 04:55 UTC, matthewfeickert reviewed
This all LGTM basically. I'm just going to take it the rest of the way and simplify somethings and try to reducde the noise of the notebook changes (we should probably move to using `jupytext` anyway).

Thanks for the PR @tomeichlersmith!

2023-04-20 04:55 UTC, matthewfeickert commented on src/pylhe/awkward.py
> +    of the pylhe API
```suggestion
    """
```

2023-04-20 04:55 UTC, matthewfeickert commented on src/pylhe/awkward.py
> +     ``pylhe`` ``v0.7.0``.
```suggestion
    .. deprecated:: 0.6.0
       Remove use of :func:`~pylhe.register_awkward` as registration is automatic.
    .. warning:: :func:`~pylhe.register_awkward` will be removed in
     ``pylhe`` ``v0.8.0``.
```

This is a change in behavior and so not something that should go into a patch release (also `pylhe` is currently `v0.5.1` not `v0.5.2`).

2023-04-20 04:55 UTC, matthewfeickert commented on src/pylhe/awkward.py
> +            so calls to `pylhe.register_awkward` can be safely removed.""",
```suggestion
"pylhe.register_awkward is deprecated as of pylhe v0.6.0 and will be removed in pylhe v0.8.0."
 + " Please remove use of pylhe.register_awkward in favor of automatic registration."
```

No one reads warnings realistically, so if they are going to be read they should be short.

2023-04-20 04:55 UTC, matthewfeickert commented on src/pylhe/awkward.py
> +    pass
```suggestion
```

Don't use `pass`.

2023-04-20 04:55 UTC, matthewfeickert commented on tests/test_awkward.py
> +    """
```suggestion
```

My point earlier was that _if_ a test needs comments then they should go in the docstring. This is a simple test and the name alone makes it clear what is happening. You wrote a good test, so this is fine as is. :+1:

2023-04-20 05:51 UTC, matthewfeickert commented on src/pylhe/awkward.py
> +        stacklevel=2,  # Raise to user level
@tomeichlersmith just to explain my changes, this should be at the level where the user will hit in when running a script in their logs easily / in the REPL.

2023-04-20 05:52 UTC, matthewfeickert approved these changes

2023-04-20 05:52 UTC, merged

2023-04-20 05:53 UTC, matthewfeickert commented
@eduardo-rodrigues Are you fine with me releasing `pylhe` `v0.6.0` with this change in it?

2023-04-20 07:46 UTC, eduardo-rodrigues commented
Totally. You are right, it does make more sense to do a 0.6.0 release given the small change in API.