docs: add developer.md
scikit-hep/pylhe pull request #266
Opened 2024-10-18 12:35 UTC by APN-Pucky

Closes: #177

2024-10-18 12:43 UTC, APN-Pucky commented
@matthewfeickert I am trying to create a 0.9.1 version and I followed your video, but https://github.com/scikit-hep/pylhe/actions/runs/11403842254/job/31731751820#step:8:46 here "Bump version" fails with
```
fatal: Failed to resolve 'v0.9.1^{}' as a valid ref.
```

2024-11-04 22:14 UTC, eduardo-rodrigues commented
It is best that @matthewfeickert helps as I have not released here so far. I tend to do my releases a different way. Can you help out @matthewfeickert?

Aside - this PR isn't done, right? Maybe better have this "admin" doc under the docs directory?

2024-11-05 06:39 UTC, matthewfeickert commented
> I am trying to create a 0.9.1 version and I followed your video, but https://github.com/scikit-hep/pylhe/actions/runs/11403842254/job/31731751820#step:8:46 here "Bump version" fails with
> 
> ```
> fatal: Failed to resolve 'v0.9.1^{}' as a valid ref.
> ```
> 
> Further I still need to figure out conda after pypi.

@APN-Pucky Sorry, I've been pretty distracted (feel free to poke me on email/Slack if I'm not responsive on GitHub as my notifications can become just a wall sometimes). Can you tell me where you're hitting this specifically in the release workflow?

2024-11-05 07:02 UTC, matthewfeickert commented
I fixed @APN-Pucky not having publishing permissions in PR https://github.com/scikit-hep/pylhe/pull/269, but I also went ahead and released [`v0.9.1`](https://github.com/scikit-hep/pylhe/releases/tag/v0.9.1) which is [now on PyPI](https://pypi.org/project/pylhe/0.9.1/).

> Further I still need to figure out conda after pypi.

@APN-Pucky the good news is that there really isn't anything to figure out. Conda-forge automatically watches PyPI for new releases and will generate a new release PR for us in a few hours. We then just review it to make sure there are no dependency changes and then we can merge it and conda-forge will then do all the building and publishing automatically.

2025-06-24 16:38 UTC, APN-Pucky commented
I will try to create a release for v0.9.2 following the steps outlined in this PR.

2025-06-24 16:48 UTC, APN-Pucky commented
@matthewfeickert Unfortunately, running the dry run bump-version for 0.9.2 fails already https://github.com/scikit-hep/pylhe/actions/runs/15856437537/job/44702856720.
```
Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
```

2025-06-24 17:07 UTC, matthewfeickert commented
Yeah, seems unhappy about the auth I guess?

```
Initializing the repository
  /usr/bin/git init /home/runner/work/pylhe/pylhe
  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint:
  hint: 	git config --global init.defaultBranch <name>
  hint:
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint:
  hint: 	git branch -m <name>
  Initialized empty Git repository in /home/runner/work/pylhe/pylhe/.git/
  /usr/bin/git remote add origin https://github.com/scikit-hep/pylhe
Disabling automatic garbage collection
  /usr/bin/git config --local gc.auto 0
Setting up auth
  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 1[28](https://github.com/scikit-hep/pylhe/actions/runs/15856820128/job/44704136263#step:2:30)
  Waiting 18 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
  Waiting 11 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled
  Error: The process '/usr/bin/git' failed with exit code 128
```

my suggestion is to check to see if there's examples in the GitHub docs to have the auth get setup correctly for workflow dispatch operations, and if not, then fall back to a simpler release workflow like given in https://learn.scientific-python.org/development/guides/gha-pure/.

2025-06-25 08:42 UTC, eduardo-rodrigues commented
Hi @matthewfeickert, is the release something you could help out, assuming the workflow still works for you as in the past? I'm quite loaded this week to investigate, as I'm at the EPPSU Open Symposium.

(I will put it on my list to look at the release when back next week ... In the end it should be easy, at least things work really smoothly and easily for Particle and DecayLanguage.)

2025-06-30 08:29 UTC, APN-Pucky commented
@matthewfeickert 

https://github.com/scikit-hep/pylhe/blob/04f357766a0192b59c9c0904a6e64ddd2885e9b7/.github/workflows/bump-version.yml#L42-L48

Apparently this uses a Personal access token, maybe it expired (if it did not work for you either).

2025-06-30 11:45 UTC, APN-Pucky commented
BTW. I personally prefer to just run the release pipeline whenever a tag is pushed (vX.Y.Z) instead of manually triggering runs. I can restructure the CI to something simpler, if the existing system can not somehow be saved.

2025-06-30 14:12 UTC, eduardo-rodrigues commented
Hi. Yep, I also reckon the present system is a bit too complicated. As I said I have things nice and easy for my packages, and @matthewfeickert seems to agree to simplify as well. Let me know if you need help.

2025-07-02 08:49 UTC, APN-Pucky commented
I just ran `tbump` manually (like the bump-version does) and pushed it. Let's see if the publish action does it's job right.

2025-07-02 14:23 UTC, eduardo-rodrigues commented
Happy it worked!

2025-07-02 14:53 UTC, eduardo-rodrigues commented
Unfortunately it's not working OK on the conda feedstock, see https://github.com/conda-forge/pylhe-feedstock/pull/13 :(.

2025-07-02 18:38 UTC, eduardo-rodrigues commented
> Unfortunately it's not working OK on the conda feedstock, see [conda-forge/pylhe-feedstock#13](https://github.com/conda-forge/pylhe-feedstock/pull/13) :(.

This has been fixed. All good there.

2026-08-17 17:34 UTC, matthewfeickert requested changes

2026-08-17 17:34 UTC, matthewfeickert commented on CONTRIBUTING.md
> +# fork scikit-hep/vector
```suggestion
# fork scikit-hep/pylhe
```

2026-08-17 17:34 UTC, matthewfeickert commented on CONTRIBUTING.md
> +pipx install hatch
Do we still want to recommend `pipx` instead of something like `uvx` or `pixi global`?

2026-08-17 17:34 UTC, matthewfeickert commented on CONTRIBUTING.md
> +You can also/alternatively run `pre-commit run` (changes only) or `pre-commit run --all-files` to check even without installing the hook.
Please use `prek` instead of `pre-commit`. The config files are the same, so it is just a search and replace of the tool names.

2026-08-17 17:34 UTC, matthewfeickert commented on developer.md
> +## PyPi
c.f. the website which has on the landing page

> The Python Package Index (PyPI) is a repository of software for the Python programming language.

```suggestion
## PyPI
```

2026-08-17 17:34 UTC, matthewfeickert commented on developer.md
> +1. Wait a few hours for automatic PR https://github.com/conda-forge/pylhe-feedstock following the PyPi release.
```suggestion
5. Manually, run the publishing action by clicking the "Run workflow" button in order to publish to Test-PyPI.
6. Optionally, inspect the URL returned after Test-PyPI uploading to check the package.
   Check that sdist and wheel are available for the new version.
7. Go to the Releases page.
   Select "Draft a new release".
8. Pick the tag created by the "Bump version" workflow (here with a "v" prefix) and click "Generate release notes".
   Tick "Set as the latest release" if this is the latest release and "Create a discussion" in the Category "Announcements".
9. Click "Publish release".
10. A build and publish to (Test)-PyPI workflow will be triggered automatically it should again upload sdist and wheel to PyPI.

## Conda

1. Wait a few hours for automatic PR https://github.com/conda-forge/pylhe-feedstock following the PyPI release.
```

2026-08-17 17:34 UTC, matthewfeickert commented on developer.md
> +## PyPi
In general I would be happy to see this workflow updated. We did this recently in https://github.com/scikit-hep/pyhf/pull/2743. Once we have validated a new release with that if people wanted to port that here that would be fine by me, but I also have no problem with people drastically simplifying the workflow to something more manual.

As described here though, it looks correct for the old existing method.

2026-08-17 21:44 UTC, APN-Pucky commented on CONTRIBUTING.md
> +You can also/alternatively run `pre-commit run` (changes only) or `pre-commit run --all-files` to check even without installing the hook.
we install pre-commit in the pyproject.toml with the dev scope currently. Should that be changed too?

2026-08-17 21:46 UTC, APN-Pucky commented on CONTRIBUTING.md
> +pipx install hatch
we could also skip that step and just write before along "install hatch via package manager/pipx/uvx/pixi"? Or list it as a pre-requisite.

2026-08-17 21:48 UTC, APN-Pucky commented on developer.md
> +## PyPi
I used it in the past, but at some point it broken and all recent releases I just did with `tbump` manually after normal CI runs pass.

2026-08-17 22:10 UTC, matthewfeickert commented on CONTRIBUTING.md
> +pipx install hatch
Yeah maybe go for general description over a prescribed installer tool choice.

2026-08-17 22:10 UTC, matthewfeickert commented on CONTRIBUTING.md
> +You can also/alternatively run `pre-commit run` (changes only) or `pre-commit run --all-files` to check even without installing the hook.
That's a good point, and yes, I think so.

2026-08-17 22:11 UTC, matthewfeickert approved these changes
@APN-Pucky Made some good suggestions on things to improve. Beyond those that he's already identified this LGTM.

2026-08-18 11:52 UTC, APN-Pucky commented on CONTRIBUTING.md
> +You can also/alternatively run `pre-commit run` (changes only) or `pre-commit run --all-files` to check even without installing the hook.
@matthewfeickert first time i am running prek and it fails, while pre-commit works flawless. I think we should stick to pre-commit due to this...
```bash
(dev) apn@APNsL13 ~/git/pylhe $ prek run --all-files
error: Failed to install hook `mypy`
  caused by: Command `/usr/bin/uv pip install --project / --directory /home/apn/.cache/prek/repos/6e48a1b38fea0dec . particle awkward vector graphviz h5py numpy` exited with an error:

[status]
exit status: 2

[stderr]
Using Python 3.14.6 environment at: /home/apn/.cache/prek/hooks/python-6XNq09SH5YSZ8WyHMVyH
error: Failed to install requirements from `build-system.requires`
Caused by: Failed to download `setuptools==84.0.0`
Caused by: Failed to read from the distribution cache
Caused by: failed to rename file from /home/apn/.cache/prek/cache/uv/.tmpl1f3hc to
/home/apn/.cache/prek/cache/uv/archive-v0/8N-pighew-IwI52P: File exists (os error
17)

(dev) apn@APNsL13 ~/git/pylhe $ pre-commit run --all-files
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/codespell-project/codespell.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/adamchainz/blacken-docs.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
check for broken symlinks................................................Passed
check json...............................................................Passed
check yaml...............................................................Passed
check toml...............................................................Passed
check xml............................................(no files to check)Skipped
debug statements (python)................................................Passed
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
codespell................................................................Passed
ruff check...............................................................Passed
ruff format..............................................................Passed
mypy.....................................................................Passed
rst ``code`` is two backticks............................................Passed
rst directives end with two colons.......................................Passed
rst ``inline code`` next to normal text..................................Passed
blacken-docs.............................................................Passed
(dev) apn@APNsL13 ~/git/pylhe $ 
```

2026-08-18 19:35 UTC, matthewfeickert commented on CONTRIBUTING.md
> +You can also/alternatively run `pre-commit run` (changes only) or `pre-commit run --all-files` to check even without installing the hook.
@APN-Pucky how are you installing `prek`? I'm having no issues and I'm also using Linux (like you):

```console
$ prek install
prek installed at `.git/hooks/pre-commit`
$ prek run --all-files
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
check for broken symlinks................................................Passed
check json...............................................................Passed
check yaml...............................................................Passed
check toml...............................................................Passed
check xml............................................(no files to check)Skipped
debug statements (python)................................................Passed
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
codespell................................................................Passed
ruff check...............................................................Passed
ruff format..............................................................Passed
mypy.....................................................................Passed
rst ``code`` is two backticks............................................Passed
rst directives end with two colons.......................................Passed
rst ``inline code`` next to normal text..................................Passed
blacken-docs.............................................................Passed
```

`prek` is quite robust and @henryiii has added it to the Scientific Python development guide: https://learn.scientific-python.org/development/guides/style/#pre-commit It is also noteably much faster.

You can also see that in a fresh Linux container setup there are no issues

```console
$ docker run --rm -ti ghcr.io/prefix-dev/pixi:latest 
root@0a391915364b:/# pixi global install git uv
├── git: 2.55.0 (installed)
│   └─ exposes: git, git-cvsserver, git-receive-pack, git-shell, git-upload-archive, git-upload-pack, gitk, scalar
└── uv: 0.12.5 (installed)
    └─ exposes: uv, uvx
root@0a391915364b:/# git clone https://github.com/APN-Pucky/pylhe.git && cd pylhe
root@0a391915364b:/pylhe# git checkout origin/developer_md -b developer_md
root@0a391915364b:/pylhe# git reset --hard 3e10d88effd3afd71820b42816d9a56fd3e6905e
HEAD is now at 3e10d88 switch to prek
root@0a391915364b:/pylhe# uv venv
Using CPython 3.14.7
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
root@0a391915364b:/pylhe# . .venv/bin/activate
(pylhe) root@0a391915364b:/pylhe# uv pip install -e '.[develop]'
(pylhe) root@0a391915364b:/pylhe# command -v prek
/pylhe/.venv/bin/prek
(pylhe) root@0a391915364b:/pylhe# prek install     
prek installed at `.git/hooks/pre-commit`
(pylhe) root@0a391915364b:/pylhe# prek run --all-files
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
check for broken symlinks................................................Passed
check json...............................................................Passed
check yaml...............................................................Passed
check toml...............................................................Passed
check xml............................................(no files to check)Skipped
debug statements (python)................................................Passed
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
codespell................................................................Passed
ruff check...............................................................Passed
ruff format..............................................................Passed
mypy.....................................................................Passed
rst ``code`` is two backticks............................................Passed
rst directives end with two colons.......................................Passed
rst ``inline code`` next to normal text..................................Passed
blacken-docs.............................................................Passed
(pylhe) root@0a391915364b:/pylhe# 
```

You'll get the same working result if you go through `hatch` as your environment manager as well.

So it seems that there's an issue with your installation or setup.

2026-08-18 19:47 UTC, APN-Pucky commented on CONTRIBUTING.md
> +You can also/alternatively run `pre-commit run` (changes only) or `pre-commit run --all-files` to check even without installing the hook.
I was in the dev env where I replaced pre-commit by prek in pyproject.toml. So `hatch shell dev` installed it for me (I followed what I wrote in CONTRIB.md here to be sure it works).

2026-08-18 21:12 UTC, matthewfeickert commented on CONTRIBUTING.md
> +You can also/alternatively run `pre-commit run` (changes only) or `pre-commit run --all-files` to check even without installing the hook.
@APN-Pucky Does it work for you if you create a fresh `dev` environment?

2026-08-19 12:50 UTC, APN-Pucky commented on CONTRIBUTING.md
> +You can also/alternatively run `pre-commit run` (changes only) or `pre-commit run --all-files` to check even without installing the hook.
surprisingly yes. I cloned all new and it works fine...

2026-08-19 13:30 UTC, merged

2026-08-19 13:58 UTC, matthewfeickert commented on CONTRIBUTING.md
> +You can also/alternatively run `pre-commit run` (changes only) or `pre-commit run --all-files` to check even without installing the hook.
Okay great. Glad to know that was transitory. :+1:

2026-08-19 13:59 UTC, matthewfeickert commented
Thank you for taking care of this @APN-Pucky!